#!/bin/sh

. "$SNAP/utils/utils.sh"
. "$SNAP/utils/endure-utils.sh" 

if [ $(get_endure) = "true" ]; then
    log "Endure is enabled, not restarting service."
    exit 0
else
    log "Endure is disabled, restarting service."
    snapctl restart reth
fi
